# active_channels : i32,
# total_channels : i32,
# frames_per_buffer : usize,
# send_ip : String,
# send_port : u16,
# meter_id : String,
# display_chan_index : i32, // index of channel to show graphics for; no
# graphics window if omitted
# sampling_frequency : u32,

total_channels = 2
frames_per_buffer = 16
send_ip = "127.0.0.1"
send_port = 7001
meter_id = "default_meter_id"
#display_chan_index = 0
sampling_frequency = 44100

# 0-indexed!
[active_channels]
0 = "L"
1 =  "R"
